plugins { id 'com.android.application' }

android {
    namespace 'com.ema.mayoreo'
    compileSdk 36

    defaultConfig {
        applicationId 'com.ema.mayoreo'
        minSdk 23
        targetSdk 36
        versionCode 5
        versionName '1.4.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
        debug {
            debuggable false
        }
    }
}
